services:
  jupyterlab:
    build:
      args:
        LSST_VERSION: al9-v29_2_1
      context: .
      dockerfile: docker/Dockerfile
    container_name: educado_jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jupyter/workspace
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=opus
      - ANTHROPIC_DEFAULT_OPUS_MODEL=claude-opus-4-6
      - LASAIR_TOKEN=${LASAIR_API_KEY}
    restart: unless-stopped
